---
- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: rpich_controller
  roles:
    - nexus
    - mysql

- hosts: rpich
  roles:
    - jenkins

- hosts: pic-1
  roles:
    - flickr-uploadr
    - gitea

