---

- name: "reload systemd"
  systemd:
    daemon_reload: "yes"

- name: "enable gitea"
  systemd:
    name: "gitea"
    enabled: "yes"

- name: "restart gitea"
  systemd:
    name: "gitea"
    state: "restarted"
