---
- name: install powershell 4 raspberry
  include_tasks: powershell_raspberry.yml
  when:
    - type == "raspberry"
  vars:
    rpi_pwsh_url: "https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/powershell-7.1.3-linux-arm32.tar.gz"
    rpi_pwsh_checksum: "sha256:DB47E8DF58FA1509FCFE34BD5A351F0DF315F995B7D48F1EA8DD1F71AA0F2D5E"
    rpi_tmp_dl_file: /tmp/powershell.tar.gz
    rpi_target_dir: /opt/microsoft/powershell
    rpi_link_dest: /usr/bin/pwsh
  tags:
    - install
    - powershell
